import type { SectionType } from './section-definitions';

export type ComponentSource = 'shadcn' | 'magicui';

export type ComponentIndexEntry = {
  id: string;
  sectionType: SectionType;
  source: ComponentSource;
  propsContract: string[];
  visualTags: string[];
  styleTags: string[];
  layoutArchetype: string;
  dependencies: string[];
};

export const COMPONENT_INDEX: ComponentIndexEntry[] = [
  {
    id: 'shadcn-hero-01',
    sectionType: 'hero',
    source: 'shadcn',
    propsContract: ['title', 'subtitle', 'ctaText', 'ctaLink?', 'badgeText?'],
    visualTags: ['centered', 'full-height', 'badge'],
    styleTags: ['modern', 'minimal'],
    layoutArchetype: 'hero-centered',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-hero-video-dialog',
    sectionType: 'hero',
    source: 'magicui',
    propsContract: ['title', 'subtitle', 'ctaText', 'videoUrl'],
    visualTags: ['centered', 'video', 'overlay'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'hero-video',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-features-01',
    sectionType: 'features',
    source: 'shadcn',
    propsContract: ['features', 'title?', 'subtitle?'],
    visualTags: ['grid', 'icon-cards'],
    styleTags: ['clean', 'product'],
    layoutArchetype: 'features-grid',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-bento-grid',
    sectionType: 'features',
    source: 'magicui',
    propsContract: ['features', 'title?', 'subtitle?'],
    visualTags: ['bento', 'grid', 'cards'],
    styleTags: ['modern', 'playful'],
    layoutArchetype: 'features-bento',
    dependencies: ['@radix-ui/react-icons'],
  },
  {
    id: 'shadcn-pricing-01',
    sectionType: 'pricing',
    source: 'shadcn',
    propsContract: ['plans', 'title?', 'subtitle?', 'currency?', 'highlightedPlanId?'],
    visualTags: ['cards', 'tiered', 'comparison'],
    styleTags: ['clean', 'product'],
    layoutArchetype: 'pricing-cards',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-pricing-spotlight',
    sectionType: 'pricing',
    source: 'magicui',
    propsContract: ['plans', 'title?', 'subtitle?', 'highlightedPlanId?'],
    visualTags: ['cards', 'spotlight', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'pricing-spotlight',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-testimonials-01',
    sectionType: 'testimonials',
    source: 'shadcn',
    propsContract: ['testimonials', 'title?', 'subtitle?', 'layout?'],
    visualTags: ['grid', 'quotes'],
    styleTags: ['minimal', 'editorial'],
    layoutArchetype: 'testimonials-grid',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-testimonials-marquee',
    sectionType: 'testimonials',
    source: 'magicui',
    propsContract: ['testimonials', 'title?', 'subtitle?'],
    visualTags: ['marquee', 'cards'],
    styleTags: ['playful', 'modern'],
    layoutArchetype: 'testimonials-marquee',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-faq-accordion',
    sectionType: 'faq',
    source: 'shadcn',
    propsContract: ['questions', 'title?', 'subtitle?'],
    visualTags: ['accordion', 'stacked'],
    styleTags: ['clean', 'support'],
    layoutArchetype: 'faq-accordion',
    dependencies: ['@radix-ui/react-collapsible'],
  },
  {
    id: 'magicui-faq-glow',
    sectionType: 'faq',
    source: 'magicui',
    propsContract: ['questions', 'title?', 'subtitle?'],
    visualTags: ['accordion', 'cards', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'faq-glow',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-footer-01',
    sectionType: 'footer',
    source: 'shadcn',
    propsContract: ['logo?', 'links?', 'social?', 'copyright?'],
    visualTags: ['multi-column', 'link-groups'],
    styleTags: ['minimal', 'corporate'],
    layoutArchetype: 'footer-columns',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-footer-gradient',
    sectionType: 'footer',
    source: 'magicui',
    propsContract: ['logo?', 'links?', 'social?', 'copyright?', 'newsletterCta?'],
    visualTags: ['gradient', 'split'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'footer-gradient',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-navigation-01',
    sectionType: 'navigation',
    source: 'shadcn',
    propsContract: ['logo', 'menuItems?', 'ctaButton?'],
    visualTags: ['top-nav', 'menu', 'sticky'],
    styleTags: ['clean', 'corporate'],
    layoutArchetype: 'nav-inline',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-navigation-glass',
    sectionType: 'navigation',
    source: 'magicui',
    propsContract: ['logo', 'menuItems?', 'ctaButton?'],
    visualTags: ['top-nav', 'glass', 'overlay'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'nav-glass',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-cta-01',
    sectionType: 'cta',
    source: 'shadcn',
    propsContract: ['title', 'buttonText', 'subtitle?', 'buttonLink?', 'background?'],
    visualTags: ['banner', 'centered'],
    styleTags: ['clean', 'product'],
    layoutArchetype: 'cta-centered',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-cta-spotlight',
    sectionType: 'cta',
    source: 'magicui',
    propsContract: ['title', 'buttonText', 'subtitle?', 'buttonLink?', 'background?'],
    visualTags: ['spotlight', 'glow', 'split'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'cta-spotlight',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-logos-01',
    sectionType: 'logos',
    source: 'shadcn',
    propsContract: ['logos', 'title?', 'subtitle?'],
    visualTags: ['logo-cloud', 'grid'],
    styleTags: ['minimal', 'trust'],
    layoutArchetype: 'logos-grid',
    dependencies: [],
  },
  {
    id: 'magicui-logos-marquee',
    sectionType: 'logos',
    source: 'magicui',
    propsContract: ['logos', 'title?', 'subtitle?'],
    visualTags: ['marquee', 'logo-cloud'],
    styleTags: ['modern', 'playful'],
    layoutArchetype: 'logos-marquee',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-team-01',
    sectionType: 'team',
    source: 'shadcn',
    propsContract: ['members', 'title?', 'subtitle?'],
    visualTags: ['grid', 'cards'],
    styleTags: ['clean', 'corporate'],
    layoutArchetype: 'team-grid',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-team-hover-cards',
    sectionType: 'team',
    source: 'magicui',
    propsContract: ['members', 'title?', 'subtitle?'],
    visualTags: ['cards', 'hover', 'gradient'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'team-hover-cards',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-stats-01',
    sectionType: 'stats',
    source: 'shadcn',
    propsContract: ['stats', 'title?', 'animated?'],
    visualTags: ['metrics', 'grid', 'numbers'],
    styleTags: ['clean', 'corporate'],
    layoutArchetype: 'stats-grid',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-stats-glow',
    sectionType: 'stats',
    source: 'magicui',
    propsContract: ['stats', 'title?', 'animated?'],
    visualTags: ['metrics', 'cards', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'stats-glow',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-contact-01',
    sectionType: 'contact',
    source: 'shadcn',
    propsContract: ['title?', 'subtitle?', 'email?', 'phone?', 'address?'],
    visualTags: ['form', 'two-column', 'details'],
    styleTags: ['clean', 'corporate'],
    layoutArchetype: 'contact-form',
    dependencies: ['@radix-ui/react-label'],
  },
  {
    id: 'magicui-contact-glow',
    sectionType: 'contact',
    source: 'magicui',
    propsContract: ['title?', 'subtitle?', 'email?', 'phone?', 'address?'],
    visualTags: ['form', 'cards', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'contact-glow',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-about-01',
    sectionType: 'about',
    source: 'shadcn',
    propsContract: ['content', 'title?', 'image?', 'stats?'],
    visualTags: ['split', 'story'],
    styleTags: ['editorial', 'minimal'],
    layoutArchetype: 'about-split',
    dependencies: [],
  },
  {
    id: 'magicui-about-spotlight',
    sectionType: 'about',
    source: 'magicui',
    propsContract: ['content', 'title?', 'image?', 'stats?'],
    visualTags: ['spotlight', 'split', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'about-spotlight',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-blog-01',
    sectionType: 'blog',
    source: 'shadcn',
    propsContract: ['posts', 'title?', 'showMore?'],
    visualTags: ['grid', 'cards'],
    styleTags: ['clean', 'editorial'],
    layoutArchetype: 'blog-grid',
    dependencies: [],
  },
  {
    id: 'magicui-blog-hover',
    sectionType: 'blog',
    source: 'magicui',
    propsContract: ['posts', 'title?', 'showMore?'],
    visualTags: ['cards', 'hover', 'gradient'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'blog-hover',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-gallery-01',
    sectionType: 'gallery',
    source: 'shadcn',
    propsContract: ['images', 'title?', 'columns?', 'lightbox?'],
    visualTags: ['grid', 'masonry'],
    styleTags: ['minimal', 'portfolio'],
    layoutArchetype: 'gallery-grid',
    dependencies: [],
  },
  {
    id: 'magicui-gallery-parallax',
    sectionType: 'gallery',
    source: 'magicui',
    propsContract: ['images', 'title?', 'columns?', 'lightbox?'],
    visualTags: ['masonry', 'parallax', 'cards'],
    styleTags: ['modern', 'playful'],
    layoutArchetype: 'gallery-parallax',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-marquee-01',
    sectionType: 'marquee',
    source: 'shadcn',
    propsContract: ['items', 'speed?', 'direction?'],
    visualTags: ['marquee', 'scroll'],
    styleTags: ['clean', 'brand'],
    layoutArchetype: 'marquee-row',
    dependencies: [],
  },
  {
    id: 'magicui-marquee-glow',
    sectionType: 'marquee',
    source: 'magicui',
    propsContract: ['items', 'speed?', 'direction?'],
    visualTags: ['marquee', 'glow', 'loop'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'marquee-glow',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-how-it-works-01',
    sectionType: 'how-it-works',
    source: 'shadcn',
    propsContract: ['steps', 'title?', 'subtitle?'],
    visualTags: ['timeline', 'steps'],
    styleTags: ['clean', 'product'],
    layoutArchetype: 'how-it-works-steps',
    dependencies: ['lucide-react'],
  },
  {
    id: 'magicui-how-it-works-glow',
    sectionType: 'how-it-works',
    source: 'magicui',
    propsContract: ['steps', 'title?', 'subtitle?'],
    visualTags: ['timeline', 'cards', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'how-it-works-glow',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-comparison-01',
    sectionType: 'comparison',
    source: 'shadcn',
    propsContract: ['rows', 'title?', 'highlights?'],
    visualTags: ['table', 'comparison'],
    styleTags: ['clean', 'corporate'],
    layoutArchetype: 'comparison-table',
    dependencies: [],
  },
  {
    id: 'magicui-comparison-highlight',
    sectionType: 'comparison',
    source: 'magicui',
    propsContract: ['rows', 'title?', 'highlights?'],
    visualTags: ['table', 'cards', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'comparison-highlight',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-integration-01',
    sectionType: 'integration',
    source: 'shadcn',
    propsContract: ['integrations', 'title?', 'subtitle?'],
    visualTags: ['logo-cloud', 'list'],
    styleTags: ['clean', 'trust'],
    layoutArchetype: 'integration-grid',
    dependencies: [],
  },
  {
    id: 'magicui-integration-glow',
    sectionType: 'integration',
    source: 'magicui',
    propsContract: ['integrations', 'title?', 'subtitle?'],
    visualTags: ['logo-cloud', 'cards', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'integration-glow',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-newsletter-01',
    sectionType: 'newsletter',
    source: 'shadcn',
    propsContract: ['ctaText', 'title?', 'subtitle?', 'placeholder?'],
    visualTags: ['form', 'inline'],
    styleTags: ['clean', 'product'],
    layoutArchetype: 'newsletter-inline',
    dependencies: ['@radix-ui/react-label'],
  },
  {
    id: 'magicui-newsletter-spotlight',
    sectionType: 'newsletter',
    source: 'magicui',
    propsContract: ['ctaText', 'title?', 'subtitle?', 'placeholder?'],
    visualTags: ['form', 'spotlight', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'newsletter-spotlight',
    dependencies: ['framer-motion'],
  },
  {
    id: 'shadcn-services-01',
    sectionType: 'services',
    source: 'shadcn',
    propsContract: ['services', 'title?', 'subtitle?'],
    visualTags: ['grid', 'cards'],
    styleTags: ['clean', 'corporate'],
    layoutArchetype: 'services-grid',
    dependencies: [],
  },
  {
    id: 'magicui-services-bento',
    sectionType: 'services',
    source: 'magicui',
    propsContract: ['services', 'title?', 'subtitle?'],
    visualTags: ['bento', 'cards', 'glow'],
    styleTags: ['modern', 'bold'],
    layoutArchetype: 'services-bento',
    dependencies: ['framer-motion'],
  },
];
