/**
 * Prompt Hints Data Module
 * Layout keywords, navigation signals, image keywords, and section layout hints.
 */

export const IMAGE_KEYWORDS = [
  'image',
  'photo',
  'photography',
  'gallery',
  'picture',
  'background image',
  'hero image',
  'cover',
  'banner',
  'lifestyle',
  'product photo',
  'album cover',
  'cover art',
  'photo shoot',
  'изображение',
  'картинка',
  'фото',
  'фотография',
  'галерея',
  'фон',
  'обложка',
  'баннер',
  'лайфстайл',
  'товарное фото',
  'обложка альбома',
  'съёмка',
  'съемка',
  'фотосессия',
];

export const LAYOUT_KEYWORDS = [
  'split',
  'left',
  'right',
  'two column',
  'two-column',
  'two columns',
  '2 column',
  '2-column',
  'image on left',
  'image on right',
  'text on left',
  'text on right',
  'grid',
  'masonry',
  'carousel',
  'slider',
  'horizontal scroll',
  'full-width',
  'full width',
  'full screen',
  'fullscreen',
  'слева',
  'справа',
  'две колонки',
  '2 колонки',
  'двухколоночный',
  'сетка',
  'мозаика',
  'мейсонри',
  'карусель',
  'слайдер',
  'горизонтальный скролл',
  'на всю ширину',
  'на весь экран',
  'полноэкранный',
];

export const NAVIGATION_SIGNALS = [
  'menu',
  'navigation',
  'navbar',
  'top bar',
  'header',
  'search icon',
  'wishlist',
  'cart',
  'profile',
  'меню',
  'навигация',
  'верхняя панель',
  'поиск',
  'корзина',
  'профиль',
  'войти',
  'личный кабинет',
];

export const SECTION_LAYOUTS: Record<string, string[]> = {
  navigation: ['Minimal top nav: logo left, links center, icons right', 'Centered nav with logo above links'],
  hero: [
    'Full-width hero with centered text and background image',
    'Split hero: text left (40%), large image right (60%)',
    'Split hero: image left (60%), text right (40%)',
    'Full-screen hero with minimal headline',
    'Hero with floating card on the right',
    'Asymmetric diagonal split hero',
  ],
  features: [
    '3-column icon cards',
    '4-column compact feature grid',
    'Alternating image/text rows',
    'Bento-style grid',
    'Single column with large icons',
  ],
  gallery: [
    'gallery',
    'portfolio',
    'photos',
    'images',
    'work',
    'showcase',
    'media',
    'unboxing',
    'meal kit',
    'meal kit unboxing',
    'recipe box',
    'unbox',
  ],
  testimonials: [
    'Carousel of testimonial cards',
    '3-column testimonial cards',
    'Featured quote with side cards',
    'Alternating quote/author layout',
    'Stacked cards with ratings',
  ],
  pricing: [
    '3-column pricing cards',
    '2-column comparison table',
    'Toggle monthly/annual with cards',
    'Expandable pricing tiers',
  ],
  cta: [
    'Centered card with glow effect',
    'Split: text left, form right',
    'Full-width banner with button',
    'Minimal text with button',
    'Two-column CTA with image',
  ],
  faq: ['Accordion list', '2-column FAQ grid', 'Card-based FAQ', 'Tabbed FAQ sections'],
  footer: [
    '4-column footer with links',
    'Minimal centered footer',
    '3-column footer with newsletter',
    'Dark gradient footer',
  ],
  about: [
    'Split: text left, image right',
    'Story with stats row',
    'Timeline-style story',
    'Centered story with highlights',
  ],
  team: [
    '3-column team cards',
    'Horizontal scroll team slider',
    'Split: portrait + bio',
    'Stacked list with avatars',
  ],
  contact: [
    'Form left, contact info right',
    'Centered form with map below',
    'Split: map left, form right',
    'Minimal contact cards',
  ],
  blog: ['Featured post + 3 cards', '3-column blog grid', 'Masonry cards', 'List with thumbnails'],
  logo: ['Logo bar row', 'Marquee logo strip', 'Grid of partner logos'],
  products: [
    'Angled album sleeves in a staggered grid with hover actions',
    'Product cards with tilted cover + price row + condition badge',
    'Crate-style product grid with overlapping covers',
    'Grid with filters sidebar and spotlight card',
  ],
  categories: [
    'Horizontal genre tag belt with scroll',
    'Rounded pill carousel with gold outlines',
    'Compact tag grid with hover glow',
  ],
  editorial: [
    'Full-width image with text overlay',
    'Split: image left, story text right',
    'Story card with quote and author',
  ],
  newsletter: ['Centered form with input + button', 'Split: text left, form right', 'Compact bar with inline input'],
};

export const SECTION_LABELS: Record<string, string> = {
  navigation: 'Navigation',
  hero: 'Hero',
  features: 'Features',
  gallery: 'Gallery',
  testimonials: 'Testimonials',
  pricing: 'Pricing',
  cta: 'CTA',
  faq: 'FAQ',
  footer: 'Footer',
  about: 'About',
  team: 'Team',
  contact: 'Contact',
  blog: 'Blog',
  logo: 'Logo',
  products: 'Products',
  categories: 'Categories',
  editorial: 'Editorial',
  newsletter: 'Newsletter',
};
