export const SECTION_KEYWORDS: Record<string, string[]> = {
  navigation: [
    'navigation',
    'navbar',
    'menu',
    'top nav',
    'top navigation',
    'header menu',
    'nav',
    'navigation bar',
    'top bar',
    'menu bar',
    'навигация',
    'меню',
    'верхнее меню',
    'верхняя панель',
    'верхняя навигация',
    'шапка',
    'хедер',
    'панель навигации',
    'меню сайта',
  ],
  hero: [
    'hero',
    'hero section',
    'hero banner',
    'hero area',
    'hero image',
    'full-width',
    'overlaid text',
    'vintage record player',
    'record player',
    'banner',
    'intro',
    'landing hero',
    'header section',
    'hero header',
    'герой',
    'первый экран',
    'главный экран',
    'баннер',
    'обложка',
    'херо',
    'хиро',
    'вводный блок',
  ],
  features: [
    'feature',
    'features',
    'services',
    'offerings',
    'benefits',
    'advantages',
    'highlights',
    'key features',
    'фичи',
    'особенности',
    'возможности',
    'услуги',
    'преимущества',
    'выгоды',
    'ключевые фичи',
    'основные преимущества',
  ],
  gallery: [
    'gallery',
    'portfolio',
    'photos',
    'images',
    'work',
    'showcase',
    'media',
    'unboxing',
    'meal kit',
    'meal kit unboxing',
    'recipe box',
    'unbox',
    'галерея',
    'портфолио',
    'фото',
    'фотографии',
    'изображения',
    'витрина',
    'работы',
    'фотогалерея',
  ],
  testimonials: [
    'testimonials',
    'reviews',
    'quotes',
    'feedback',
    'client stories',
    'отзывы',
    'отзывами',
    'отзывов',
    'отзывам',
    'рецензии',
    'мнения',
    'отклики',
    'истории клиентов',
  ],
  pricing: [
    'pricing',
    'plans',
    'packages',
    'tiers',
    'subscription',
    'цены',
    'тарифы',
    'планы',
    'стоимость',
    'стоимость услуг',
    'прайс',
    'прайс-лист',
    'подписка',
    'пакеты',
  ],
  cta: [
    'cta',
    'call to action',
    'signup',
    'join',
    'get started',
    'book now',
    'призыв к действию',
    'регистрация',
    'записаться',
    'начать',
    'начать работу',
    'получить доступ',
    'заказать',
    'оставить заявку',
    'купить',
  ],
  faq: [
    'faq',
    'questions',
    'q&a',
    'help',
    'support',
    'вопросы',
    'вопрос-ответ',
    'вопросы и ответы',
    'частые вопросы',
    'часто задаваемые вопросы',
    'помощь',
    'поддержка',
  ],
  footer: [
    'footer',
    'bottom',
    'bottom bar',
    'site footer',
    'футер',
    'подвал',
    'низ сайта',
    'низ страницы',
    'нижняя часть',
    'нижняя панель',
  ],
  about: [
    'about',
    'story',
    'our story',
    'mission',
    'values',
    'about us',
    'о нас',
    'о компании',
    'о бренде',
    'о проекте',
    'история',
    'наша история',
    'миссия',
    'ценности',
  ],
  team: [
    'team',
    'people',
    'staff',
    'leaders',
    'команда',
    'наша команда',
    'сотрудники',
    'люди',
    'руководство',
    'эксперты',
    'коллектив',
    'состав команды',
  ],
  contact: [
    'contact',
    'get in touch',
    'reach out',
    'form',
    'контакты',
    'контакт',
    'связь',
    'обратная связь',
    'форма',
    'форма связи',
    'написать нам',
    'свяжитесь',
    'контактная информация',
  ],
  blog: [
    'blog',
    'news',
    'articles',
    'updates',
    'блог',
    'новости',
    'статьи',
    'обновления',
    'публикации',
    'посты',
  ],
  logo: [
    'logo',
    'clients',
    'partners',
    'brands',
    'логотипы',
    'логотипы клиентов',
    'логотипы партнеров',
    'клиенты',
    'партнеры',
    'бренды',
  ],
  products: [
    'products',
    'product grid',
    'product listing',
    'product cards',
    'featured',
    'featured records',
    'vinyl cards',
    'album cards',
    'record cards',
    'bestsellers',
    'featured collection',
    'records grid',
    'album grid',
    'catalog',
    'товары',
    'товар',
    'продукты',
    'каталог',
    'каталог товаров',
    'витрина',
    'карточки товаров',
    'товарные карточки',
    'товарная сетка',
    'ассортимент',
  ],
  categories: [
    'categories',
    'category cards',
    'category carousel',
    'collections',
    'genres',
    'genre',
    'genre carousel',
    'music genres',
    'carousel',
    'slider',
    'horizontal scroll',
    'filter buttons',
    'filter tags',
    'tags',
    'pills',
    'chips',
    'rounded tags',
    'категории',
    'категории товаров',
    'коллекции',
    'жанры',
    'жанр',
    'фильтры',
    'теги',
    'подборки',
    'подборки товаров',
  ],
  editorial: [
    'editorial',
    'story section',
    'magazine',
    'article',
    'редакционный',
    'статья',
    'история',
    'журнал',
    'публикация',
    'лонгрид',
    'редакционная статья',
  ],
  newsletter: [
    'newsletter',
    'subscribe',
    'email signup',
    'mailing list',
    'рассылка',
    'подписка',
    'подписаться',
    'email рассылка',
    'почтовая рассылка',
    'новостная рассылка',
    'подписка на рассылку',
  ],
};
