export const SECTION_KEYWORDS: Record<string, string[]> = {
  navigation: [
    'navigation',
    'navbar',
    'menu',
    'top nav',
    'top navigation',
    'header menu',
    'nav',
    'navigation bar',
    'top bar',
    'menu bar',
    'навигация',
    'меню',
    'верхнее меню',
    'верхняя панель',
    'шапка',
    'хедер',
    'панель навигации',
    'верхняя навигация',
  ],
  hero: [
    'hero',
    'hero section',
    'hero banner',
    'hero area',
    'hero image',
    'full-width',
    'overlaid text',
    'vintage record player',
    'record player',
    'banner',
    'intro',
    'landing hero',
    'header section',
    'hero header',
    'герой',
    'первый экран',
    'главный экран',
    'баннер',
    'обложка',
    'херо',
    'хиро',
    'вводный блок',
  ],
  features: [
    'feature',
    'features',
    'services',
    'offerings',
    'benefits',
    'advantages',
    'highlights',
    'key features',
    'фичи',
    'преимущества',
    'особенности',
    'возможности',
    'услуги',
    'ключевые фичи',
    'основные преимущества',
  ],
  gallery: [
    'gallery',
    'portfolio',
    'photos',
    'images',
    'work',
    'showcase',
    'media',
    'unboxing',
    'meal kit',
    'meal kit unboxing',
    'recipe box',
    'unbox',
    'галерея',
    'портфолио',
    'фото',
    'фотографии',
    'изображения',
    'витрина',
    'работы',
    'фотогалерея',
  ],
  testimonials: [
    'testimonials',
    'reviews',
    'quotes',
    'feedback',
    'client stories',
    'отзывы',
    'отзывами',
    'отзывов',
    'отзывам',
    'рецензии',
    'мнения',
    'отклики',
    'истории клиентов',
  ],
  pricing: [
    'pricing',
    'plans',
    'packages',
    'tiers',
    'subscription',
    'цены',
    'тарифы',
    'планы',
    'стоимость',
    'прайс',
    'подписка',
  ],
  cta: [
    'cta',
    'call to action',
    'signup',
    'join',
    'get started',
    'book now',
    'призыв к действию',
    'регистрация',
    'записаться',
    'начать',
    'начать работу',
    'получить доступ',
    'заказать',
  ],
  faq: [
    'faq',
    'questions',
    'q&a',
    'help',
    'support',
    'вопросы',
    'вопросы и ответы',
    'частые вопросы',
    'помощь',
    'поддержка',
  ],
  footer: [
    'footer',
    'bottom',
    'bottom bar',
    'site footer',
    'футер',
    'подвал',
    'низ сайта',
    'нижняя часть',
    'нижняя панель',
  ],
  about: [
    'about',
    'story',
    'our story',
    'mission',
    'values',
    'about us',
    'о нас',
    'история',
    'наша история',
    'миссия',
    'ценности',
    'о компании',
  ],
  team: [
    'team',
    'people',
    'staff',
    'leaders',
    'команда',
    'сотрудники',
    'люди',
    'руководство',
    'эксперты',
    'коллектив',
  ],
  contact: [
    'contact',
    'get in touch',
    'reach out',
    'form',
    'контакты',
    'связаться',
    'обратная связь',
    'форма',
    'свяжитесь',
    'контактная информация',
  ],
  blog: [
    'blog',
    'news',
    'articles',
    'updates',
    'блог',
    'новости',
    'статьи',
    'обновления',
    'публикации',
  ],
  logo: [
    'logo',
    'clients',
    'partners',
    'brands',
    'логотипы',
    'логотипы клиентов',
    'клиенты',
    'партнеры',
    'бренды',
  ],
  products: [
    'products',
    'product grid',
    'product listing',
    'product cards',
    'featured',
    'featured records',
    'vinyl cards',
    'album cards',
    'record cards',
    'bestsellers',
    'featured collection',
    'records grid',
    'album grid',
    'catalog',
    'товары',
    'продукты',
    'каталог',
    'витрина',
    'карточки товаров',
    'товарные карточки',
    'товарная сетка',
    'ассортимент',
  ],
  categories: [
    'categories',
    'category cards',
    'category carousel',
    'collections',
    'genres',
    'genre',
    'genre carousel',
    'music genres',
    'carousel',
    'slider',
    'horizontal scroll',
    'filter buttons',
    'filter tags',
    'tags',
    'pills',
    'chips',
    'rounded tags',
    'категории',
    'коллекции',
    'жанры',
    'жанр',
    'категории товаров',
    'фильтры',
    'теги',
  ],
  editorial: [
    'editorial',
    'story section',
    'magazine',
    'article',
    'редакционный',
    'история',
    'статья',
    'журнал',
    'публикация',
    'лонгрид',
  ],
  newsletter: [
    'newsletter',
    'subscribe',
    'email signup',
    'mailing list',
    'рассылка',
    'подписка',
    'подписаться',
    'email подписка',
    'почтовая рассылка',
  ],
};
