export const SECTION_KEYWORDS: Record<string, string[]> = {
  navigation: [
    'navigation',
    'navbar',
    'menu',
    'top nav',
    'top navigation',
    'header menu',
    'nav',
    'navigation bar',
    'top bar',
    'menu bar',
    'навигация',
    'навигационное меню',
    'верхнее меню',
    'хедер',
    'шапка',
    'меню',
  ],
  hero: [
    'hero',
    'hero section',
    'hero banner',
    'hero area',
    'hero image',
    'full-width',
    'overlaid text',
    'vintage record player',
    'record player',
    'banner',
    'intro',
    'landing hero',
    'header section',
    'hero header',
    'герой',
    'хиро',
    'баннер',
    'первый экран',
    'шапка',
    'заголовок',
  ],
  features: [
    'feature',
    'features',
    'services',
    'offerings',
    'benefits',
    'advantages',
    'highlights',
    'key features',
    'преимущества',
    'особенности',
    'услуги',
    'предложения',
    'выгоды',
    'фичи',
    'ключевые фичи',
  ],
  gallery: [
    'gallery',
    'portfolio',
    'photos',
    'images',
    'work',
    'showcase',
    'media',
    'unboxing',
    'meal kit',
    'meal kit unboxing',
    'recipe box',
    'unbox',
    'галерея',
    'портфолио',
    'фото',
    'фотографии',
    'изображения',
    'распаковка',
    'витрина',
  ],
  testimonials: [
    'testimonials',
    'reviews',
    'quotes',
    'feedback',
    'client stories',
    'отзывы',
    'отзывами',
    'мнения',
    'рекомендации',
    'истории клиентов',
  ],
  pricing: [
    'pricing',
    'plans',
    'packages',
    'tiers',
    'subscription',
    'цены',
    'тарифы',
    'прайс',
    'пакеты',
  ],
  cta: [
    'cta',
    'call to action',
    'signup',
    'join',
    'get started',
    'book now',
    'призыв к действию',
    'записаться',
    'оставить заявку',
    'получить консультацию',
    'заказать',
  ],
  faq: [
    'faq',
    'questions',
    'q&a',
    'help',
    'support',
    'вопросы',
    'вопросы и ответы',
    'частые вопросы',
    'помощь',
  ],
  footer: [
    'footer',
    'bottom',
    'bottom bar',
    'site footer',
    'футер',
    'подвал',
  ],
  about: [
    'about',
    'story',
    'our story',
    'mission',
    'values',
    'about us',
    'о нас',
    'история',
    'миссия',
    'ценности',
  ],
  team: [
    'team',
    'people',
    'staff',
    'leaders',
    'команда',
    'сотрудники',
    'персонал',
  ],
  contact: [
    'contact',
    'get in touch',
    'reach out',
    'form',
    'контакты',
    'связаться',
    'обратная связь',
    'форма',
  ],
  blog: [
    'blog',
    'news',
    'articles',
    'updates',
    'блог',
    'новости',
    'статьи',
  ],
  logo: [
    'logo',
    'clients',
    'partners',
    'brands',
    'логотипы',
    'клиенты',
    'партнеры',
    'бренды',
  ],
  products: [
    'products',
    'product grid',
    'product listing',
    'product cards',
    'featured',
    'featured records',
    'vinyl cards',
    'album cards',
    'record cards',
    'bestsellers',
    'featured collection',
    'records grid',
    'album grid',
    'catalog',
    'товары',
    'продукты',
    'каталог',
    'витрина',
    'карточки товаров',
    'пластинки',
  ],
  categories: [
    'categories',
    'category cards',
    'category carousel',
    'collections',
    'genres',
    'genre',
    'genre carousel',
    'music genres',
    'carousel',
    'slider',
    'horizontal scroll',
    'filter buttons',
    'filter tags',
    'tags',
    'pills',
    'chips',
    'rounded tags',
    'категории',
    'категории товаров',
    'коллекции',
    'жанры',
    'теги',
    'плашки',
    'фильтры',
  ],
  editorial: [
    'editorial',
    'story section',
    'magazine',
    'article',
    'редакционный',
    'история бренда',
    'журнал',
  ],
  newsletter: [
    'newsletter',
    'subscribe',
    'email signup',
    'mailing list',
    'рассылка',
    'подписка',
    'подписаться',
  ],
};
