/**
 * Theme Keywords Data Module
 * Contains theme detection keywords for EN and RU languages
 */

// Theme detection keywords (EN)
export const THEME_KEYWORDS: Record<string, string[]> = {
  furniture: [
    'furniture',
    'sofa',
    'chair',
    'table',
    'storage',
    'seating',
    'decor',
    'cabinet',
    'interior',
    'scandinavian',
    'mid-century',
    'furniture brand',
  ],
  vinyl: [
    'vinyl',
    'record',
    'records',
    'turntable',
    'record player',
    'lp',
    'record store',
    'music store',
    'hi-fi',
    'music',
    'vinyl shop',
  ],
  ecommerce: [
    'e-commerce',
    'ecommerce',
    'shop',
    'store',
    'product',
    'cart',
    'checkout',
    'marketplace',
    'retail',
    'catalog',
    'catalogue',
    'ecommerce site',
  ],
  fashion: [
    'fashion',
    'clothing',
    'apparel',
    'shoes',
    'accessories',
    'lookbook',
    'boutique',
    'streetwear',
    'luxury fashion',
  ],
  beauty: [
    'beauty',
    'cosmetics',
    'makeup',
    'skincare',
    'fragrance',
    'perfume',
    'wellness',
    'spa',
  ],
  electronics: [
    'electronics',
    'gadget',
    'phone',
    'smartphone',
    'laptop',
    'smart home',
    'camera',
    'device',
    'tech hardware',
    'wearable',
  ],
  food: [
    'food',
    'grocery',
    'beverage',
    'coffee',
    'tea',
    'snack',
    'bakery',
  ],
  photography: [
    'photography',
    'photographer',
    'photo shoot',
    'photoshoot',
    'portfolio',
    'gallery',
    'freelance',
    'creative',
    'visual',
    'squarespace',
    'photo',
  ],
  industrial: [
    'industrial',
    'energy',
    'oil',
    'gas',
    'power',
    'refinery',
    'pipeline',
    'manufacturing',
    'factory',
    'engineering',
    'industry',
    'utilities',
    'infrastructure',
  ],
  hotel: [
    'hotel',
    'hospitality',
    'resort',
    'boutique hotel',
    'spa',
    'accommodation',
    'booking',
    'travel',
    'stay',
  ],
  tech: [
    'tech',
    'saas',
    'startup',
    'software',
    'app',
    'platform',
    'dashboard',
    'analytics',
    'ai',
    'cloud',
    'devtools',
    'web3',
    'blockchain',
    'crypto',
  ],
  medical: [
    'medical',
    'health',
    'clinic',
    'hospital',
    'doctor',
    'wellness',
    'healthcare',
    'pharmacy',
  ],
  restaurant: [
    'restaurant',
    'cafe',
    'bistro',
    'bar',
    'menu',
    'dining',
  ],
  realestate: [
    'real estate',
    'property',
    'realty',
    'apartments',
    'housing',
    'rent',
  ],
  finance: [
    'finance',
    'fintech',
    'bank',
    'banking',
    'investment',
    'insurance',
  ],
  education: [
    'education',
    'course',
    'academy',
    'school',
    'learning',
    'online course',
    'e-learning',
  ],
  default: [
    'website',
    'landing',
    'page',
    'design',
    'site',
  ],
};

// Theme detection keywords (RU)
export const THEME_KEYWORDS_RU: Record<string, string[]> = {
  furniture: [
    'мебель',
    'мебельный',
    'мебельного',
    'диван',
    'кресло',
    'стол',
    'шкаф',
    'хранение',
    'интерьер',
    'дизайн интерьера',
    'декор',
    'скандинавский',
    'скандинавском',
    'сканди',
    'мебельный бренд',
  ],
  vinyl: [
    'винил',
    'винила',
    'винилу',
    'виниловый',
    'виниловые',
    'виниловых',
    'пластинка',
    'пластинки',
    'пластинок',
    'пластинками',
    'проигрыватель',
    'проигрывателя',
    'проигрывателей',
    'магазин винила',
    'магазин виниловых пластинок',
    'магазин пластинок',
    'виниловый магазин',
    'музыкальный магазин',
    'музыка',
    'хай-фай',
    'грампластинка',
    'грампластинки',
  ],
  ecommerce: [
    'интернет-магазин',
    'интернет-магазина',
    'интернет магазин',
    'онлайн магазин',
    'онлайн-магазин',
    'онлайн-магазина',
    'магазин',
    'магазина',
    'маркетплейс',
    'маркетплейса',
    'витрина',
    'витрины',
    'корзина',
    'корзины',
    'оформление заказа',
    'каталог',
    'каталога',
    'товары',
    'товаров',
    'покупка',
    'покупки',
    'заказ',
    'заказы',
    'заказов',
    'доставка товаров',
  ],
  fashion: [
    'мода',
    'модной',
    'одежда',
    'одежды',
    'бренд одежды',
    'обувь',
    'аксессуары',
    'бутик одежды',
    'бутик моды',
    'бутик модной одежды',
    'бутика одежды',
    'бутика модной одежды',
    'лукбук',
    'стритвир',
  ],
  beauty: [
    'красота',
    'красоты',
    'косметика',
    'косметология',
    'косметический',
    'косметологии',
    'косметологический',
    'макияж',
    'уход за кожей',
    'уход за лицом',
    'уход за волосами',
    'уход',
    'парфюм',
    'аромат',
    'салон красоты',
    'салон',
    'салона',
    'спа',
    'парикмахерская',
    'маникюр',
    'педикюр',
    'бьюти',
  ],
  electronics: [
    'электроника',
    'электроники',
    'гаджет',
    'гаджеты',
    'смартфон',
    'телефон',
    'ноутбук',
    'камера',
    'умный дом',
    'девайс',
    'девайсы',
    'техника',
  ],
  food: [
    'еда',
    'еды',
    'продукты',
    'продуктов',
    'продуктовый',
    'продуктовый магазин',
    'бакалея',
    'доставка еды',
    'доставки еды',
    'еда на вынос',
    'еда на доставку',
    'фуд',
    'фудтех',
    'фастфуд',
    'street food',
    'напитки',
    'кофе',
    'чай',
    'пекарня',
    'кулинария',
  ],
  photography: [
    'фотография',
    'фотограф',
    'фотографы',
    'фотосессия',
    'фотосъемка',
    'фотосъёмка',
    'съемка',
    'съёмка',
    'фото',
    'фотостудия',
    'фотостудии',
    'фотоуслуги',
    'портфолио',
  ],
  industrial: [
    'промышленность',
    'промышленный',
    'промышленной',
    'производство',
    'завод',
    'фабрика',
    'энергетика',
    'энергетики',
    'энергетический',
    'энергетическая',
    'нефть',
    'газ',
    'нефтегаз',
    'нефтегазовый',
    'добыча',
    'инфраструктура',
    'инжиниринг',
    'машиностроение',
    'энергокомпания',
  ],
  hotel: [
    'отель',
    'отеля',
    'гостиница',
    'гостиницы',
    'гостиничный',
    'отельный',
    'курорт',
    'бутик-отель',
    'бутик-отеля',
    'бронирование',
    'проживание',
    'отдых',
    'туризм',
    'спа',
    'номер',
    'номера',
  ],
  tech: [
    'технологии',
    'тех',
    'технологический',
    'технологичная',
    'айти',
    'it',
    'стартап',
    'софт',
    'приложение',
    'разработка',
    'разработки',
    'разработчик',
    'разработчики',
    'платформа',
    'цифровая платформа',
    'цифровые решения',
    'дешборд',
    'аналитика',
    'искусственный интеллект',
    'ии',
    'облако',
    'облачный',
    'цифровой',
  ],
  medical: [
    'медицина',
    'медицинский',
    'медицинская',
    'медицинского',
    'клиника',
    'клиники',
    'больница',
    'врач',
    'стоматология',
    'здоровье',
    'здоровья',
    'аптека',
    'медцентр',
  ],
  restaurant: [
    'ресторан',
    'ресторана',
    'ресторанный',
    'ресторанного',
    'кафе',
    'кафетерий',
    'бар',
    'бара',
    'барный',
    'бистро',
    'кафейный',
    'меню',
    'кухня',
    'кухни',
    'гастрономия',
    'гастрономический',
    'гастробар',
    'гастропаб',
    'столовая',
    'общепит',
    'заведение',
    'заведения',
    'фудкорт',
  ],
  realestate: [
    'недвижимость',
    'недвижимости',
    'риэлтор',
    'риелтор',
    'агентство недвижимости',
    'агентства недвижимости',
    'жилье',
    'жильё',
    'квартира',
    'квартиры',
    'аренда',
    'аренды',
    'новостройки',
    'новостройка',
    'жилой комплекс',
    'жк',
    'застройщик',
    'застройщики',
    'продажа недвижимости',
    'продажа квартир',
    'объекты недвижимости',
  ],
  finance: [
    'финансы',
    'финансовый',
    'финансовая',
    'финансового',
    'финансовых',
    'финтех',
    'банк',
    'банковский',
    'банковская',
    'банковского',
    'банковских',
    'инвестиции',
    'инвестиционный',
    'страхование',
    'страховой',
    'страховка',
    'кредит',
    'платеж',
    'платежи',
    'платежный',
    'платежная',
    'платёжный',
    'платёжная',
    'кошелек',
    'кошелёк',
  ],
  education: [
    'образование',
    'обучение',
    'обучение онлайн',
    'онлайн обучение',
    'курс',
    'курсы',
    'курсов',
    'школа',
    'онлайн школа',
    'онлайн-школа',
    'академия',
    'обучающий',
    'онлайн курс',
    'онлайн-курс',
    'учебный',
  ],
  default: [
    'сайт',
    'лендинг',
    'страница',
    'веб-сайт',
    'дизайн',
  ],
};

/**
 * Get merged keywords (EN + RU) for all themes
 * Call this once at initialization instead of mutating at import time
 */
export function getMergedKeywords(): Record<string, string[]> {
  const merged: Record<string, string[]> = {};

  // Copy EN keywords
  for (const [theme, keywords] of Object.entries(THEME_KEYWORDS)) {
    merged[theme] = [...keywords];
  }

  // Add RU keywords
  for (const [theme, keywords] of Object.entries(THEME_KEYWORDS_RU)) {
    if (!merged[theme]) {
      merged[theme] = [];
    }
    merged[theme].push(...keywords);
  }

  return merged;
}
